import type { MetadataRoute } from "next"

// Add to Home Screen. `standalone` is what removes Safari's chrome so the
// session screen actually owns the viewport — without it the URL bar eats the
// commit button's safe-area padding every time the page scrolls.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Level Up — IRL Player",
    short_name: "Level Up",
    description: "Strength and power logging for one real human.",
    start_url: "/train",
    display: "standalone",
    orientation: "portrait",
    background_color: "#1E1C18",
    theme_color: "#1E1C18",
    // Both routes are generated by app/icon.tsx and app/apple-icon.tsx, so
    // there are no binary assets to keep in sync with the palette.
    icons: [
      { src: "/icon", sizes: "512x512", type: "image/png" },
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "maskable" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  }
}
