ALTER TABLE "Rule" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "RuleRun" ADD COLUMN "ruleVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "RuleRun" ADD COLUMN "causationDepth" INTEGER NOT NULL DEFAULT 0;
