import SwiftUI
import LifeOSCompanionCore

struct MacDashboard: View {
    @EnvironmentObject var model: MacCompanionModel
    private let linen = Color(red: 0.914, green: 0.89, blue: 0.847), surface = Color(red: 0.969, green: 0.957, blue: 0.933), ink = Color(red: 0.173, green: 0.149, blue: 0.125), cognac = Color(red: 0.561, green: 0.42, blue: 0.29), petrol = Color(red: 0.102, green: 0.165, blue: 0.208)
    var body: some View {
        ZStack { linen.ignoresSafeArea(); VStack(spacing: 0) { header; ScrollView { HStack(alignment: .top, spacing: 20) { connectors; statusCard.frame(width: 245) }.padding(28) } } }.foregroundStyle(ink)
    }
    private var header: some View { HStack { Text("Life OS Companion").font(.system(size: 19, design: .serif)); Spacer(); Circle().fill(model.errorCode == nil ? Color.green.opacity(0.7) : cognac).frame(width: 8); Text(model.errorCode == nil ? "Collector ready" : "Needs attention").font(.caption) }.padding(.horizontal, 24).frame(height: 54).background(surface) }
    private var connectors: some View { VStack(alignment: .leading, spacing: 14) { Text("Your Mac, quietly connected").font(.system(size: 30, weight: .regular, design: .serif)); Text("Only normalized records leave this Mac. Raw databases, files, audio, attachments, and local paths stay here.").foregroundStyle(.secondary).frame(maxWidth: 540, alignment: .leading); ForEach(model.statuses) { status in HStack { Image(systemName: icon(status.source)).frame(width: 28).foregroundStyle(cognac); VStack(alignment: .leading) { Text(title(status.source)); Text(status.permissionStatus.rawValue.replacingOccurrences(of: "_", with: " ")).font(.caption).foregroundStyle(.secondary) }; Spacer(); Toggle("", isOn: Binding(get: { status.enabled }, set: { model.setEnabled(status.source, enabled: $0) })).labelsHidden() }.padding(16).background(surface).clipShape(RoundedRectangle(cornerRadius: 12)) }; if !model.signedIn { Button("Sign in to Life OS") { model.signIn() }.buttonStyle(CognacButton(color: cognac)) } }.frame(maxWidth: .infinity, alignment: .leading) }
    private var statusCard: some View { VStack(alignment: .leading, spacing: 18) { Text("Collection status").font(.headline); Text("\(model.pendingCount)").font(.system(size: 42, design: .serif)).foregroundStyle(Color(red: 0.77, green: 0.65, blue: 0.45)); Text("records waiting to sync").font(.caption).foregroundStyle(.white.opacity(0.65)); Divider().overlay(.white.opacity(0.15)); Button(model.isPaused ? "Resume collection" : "Pause collection") { model.togglePause() }.buttonStyle(CognacButton(color: cognac)); Button("Retry now") { Task { await model.syncNow() } }.buttonStyle(.plain).foregroundStyle(.white); Button("Repair background service") { model.repairBackgroundService() }.buttonStyle(.plain).foregroundStyle(.white); if let date = model.lastSuccessfulSync { Text("Last synced \(date.formatted(.relative(presentation: .named)))").font(.caption).foregroundStyle(.white.opacity(0.65)) } }.padding(22).foregroundStyle(.white).background(petrol).clipShape(RoundedRectangle(cornerRadius: 12)) }
    private func title(_ source: ConnectorSource) -> String { source.rawValue.replacingOccurrences(of: "_", with: " ").capitalized }
    private func icon(_ source: ConnectorSource) -> String { switch source { case .imessage: "message.fill"; case .whatsapp: "bubble.left.and.bubble.right.fill"; case .documents: "folder.fill"; case .voiceJournal: "waveform"; case .photos: "photo.fill"; case .callHistory: "phone.fill"; default: "circle.grid.2x2.fill" } }
}
private struct CognacButton: ButtonStyle { let color: Color; func makeBody(configuration: Configuration) -> some View { configuration.label.padding(.horizontal, 18).padding(.vertical, 9).background(configuration.isPressed ? color.opacity(0.8) : color).foregroundStyle(.white).clipShape(Capsule()) } }
